{{ config(
  materialized='table')}}

WITH cte AS (
    (SELECT 
        academic_year,
        age,
        alternate_number_preferably_whatsapp,
        any_preferred_loc_for_employment,
        are_you_currently_working_job_own_business_etc,
        are_you_intrested_in_doing_apprentice_naps_,
        assessment_conducted,
        block_of_residence,
        can_send_the_updates,
        category,
        city_of_residence,
        class,
        collected_email_id,
        completed_ojt_internship_in_11_12,
        concent_for_lahi_contact,
        course_for_training,
        course_full_time_part_time,
        course_name_if_other,
        date_of_birth,
        date_of_exit_interview,
        details_of_current_employment_title,
        details_of_employment,
        details_ojt_internship_employer,
        different_program_opportunities,
        district,
        district_of_residence,
        division,
        does_field_study_hve_voc_sub,
        employment_portalname,
        end_date,
        exit_student_id,
        exit_survey_status,
        father_name,
        field_studies_contain_voc_subjects,
        firm_city_location,
        firm_contact_number,
        firm_organisation_name,
        first_name,
        fullname,
        gender,
        hve_registered_on_employment_portal,
        id,
        index,
        interested_in_career_counseling,
        interested_in_job_or_self_employment_after_10_12,
        interested_in_skill_training,
        internship_completed_sector,
        intrested_in_job_or_self_employment_post12th,
        is_assessment_required,
        is_fulltime_willingness,
        is_relevant_to_voc_course,
        is_vs_completed,
        job_role,
        kind_of_employment_are_you_interested_in,
        last_name,
        middle_name,
        mother_name,
        other_course,
        other_educ_stream_please_specify,
        other_reason_not_conti_ve_specify,
        other_reasons,
        other_sector,
        other_sectors_if_any,
        others_if_any,
        overall_ve_experience_in_school,
        parent_index,
        parent_mobile_no,
        particular_location_for_employment,
        preferred_location_for_employment,
        primary_contact_number,
        reason_not_conti_high_educ,
        reason_not_conti_high_educ_failed_in_current,
        reason_not_conti_high_educ_family_not_allow,
        reason_not_conti_high_educ_financial,
        reason_not_conti_high_educ_marriage,
reason_not_conti_high_educ_need_a_job,
reason_not_conti_high_educ_not_interested,
reason_not_conti_high_educ_other,
reason_not_conti_high_educ_school_till_10th_only,
reasons_for_not_conti_ve,
reasons_not_conti_ve_in_11th,
registered_on_naps_portal_for_apprentices,
religion,
remark,
school_name,
school_udise,
sector,
sector_for_skill_training,
sector_for_training,
sectors_of_employment,
select_sector,
skill_training_type,
specify_other_stream,
start_date,
state,
stream_name,
stream_of_education,
stream_of_higher_educ,
student_unique_id,
student_unique_id_new,
studentaddress,
studentwano,
submission_id,
submission_time,
submission_uuid,
survey_completed_by_student_or_parent,
today,
topics_of_interest,
trainingtype,
uuid,
vc_name,
vt_mobile_number,
vt_name,
vtp_name,
want_to_know_abtpgms_for_jobsn_cont_edu,
wanttoknowaboutopportunities,
wanttoknowabtskillsunivbygvt,
which_course_will_you_pursue,
will_be_fulltime,
will_cont_same_sector,
will_cont_voc_edu,
willing_to_cont_skill_training,
willing_to_conti_part_time_job_while_doing_educ,
willing_to_conti_ve_in_11th,
willing_to_go_for_tech_high_edu,
would_you_conti_high_edu
     FROM {{ref("mart_kobo_ex.survey_data")}})
    UNION ALL
    (SELECT 
    academic_year,
age,
alternate_number_preferably_whatsapp,
any_preferred_loc_for_employment,
are_you_currently_working_job_own_business_etc,
are_you_intrested_in_doing_apprentice_naps_,
assessment_conducted,
block_of_residence,
can_send_the_updates,
category,
city_of_residence,
class,
collected_email_id,
completed_ojt_internship_in_11_12,
concent_for_lahi_contact,
course_for_training,
course_full_time_part_time,
course_name_if_other,
date_of_birth,
date_of_exit_interview,
details_of_current_employment_title,
details_of_employment,
details_ojt_internship_employer,
different_program_opportunities,
district,
district_of_residence,
division,
does_field_study_hve_voc_sub,
employment_portalname,
end_date,
exit_student_id,
exit_survey_status,
father_name,
field_studies_contain_voc_subjects,
firm_city_location,
firm_contact_number,
firm_organisation_name,
first_name,
fullname,
gender,
hve_registered_on_employment_portal,
id,
index,
interested_in_career_counseling,
interested_in_job_or_self_employment_after_10_12,
interested_in_skill_training,
internship_completed_sector,
intrested_in_job_or_self_employment_post12th,
is_assessment_required,
is_fulltime_willingness,
is_relevant_to_voc_course,
is_vs_completed,
job_role,
kind_of_employment_are_you_interested_in,
last_name,
middle_name,
mother_name,
other_course,
other_educ_stream_please_specify,
other_reason_not_conti_ve_specify,
other_reasons,
other_sector,
other_sectors_if_any,
others_if_any,
overall_ve_experience_in_school,
parent_index,
parent_mobile_no,
particular_location_for_employment,
preferred_location_for_employment,
primary_contact_number,
reason_not_conti_high_educ,
reason_not_conti_high_educ_failed_in_current,
reason_not_conti_high_educ_family_not_allow,
reason_not_conti_high_educ_financial,
reason_not_conti_high_educ_marriage,
reason_not_conti_high_educ_need_a_job,
reason_not_conti_high_educ_not_interested,
reason_not_conti_high_educ_other,
reason_not_conti_high_educ_school_till_10th_only,
reasons_for_not_conti_ve,
reasons_not_conti_ve_in_11th,
registered_on_naps_portal_for_apprentices,
religion,
remark,
school_name,
school_udise,
sector,
sector_for_skill_training,
sector_for_training,
sectors_of_employment,
select_sector,
skill_training_type,
specify_other_stream,
start_date,
state,
stream_name,
stream_of_education,
stream_of_higher_educ,
student_unique_id,
student_unique_id_new,
studentaddress,
studentwano,
submission_id,
submission_time,
submission_uuid,
survey_completed_by_student_or_parent,
today,
topics_of_interest,
trainingtype,
uuid,
vc_name,
vt_mobile_number,
vt_name,
vtp_name,
want_to_know_abtpgms_for_jobsn_cont_edu,
wanttoknowaboutopportunities,
wanttoknowabtskillsunivbygvt,
which_course_will_you_pursue,
will_be_fulltime,
will_cont_same_sector,
will_cont_voc_edu,
willing_to_cont_skill_training,
willing_to_conti_part_time_job_while_doing_educ,
willing_to_conti_ve_in_11th,
willing_to_go_for_tech_high_edu,
would_you_conti_high_edu

    FROM {{ref("mart_lh_mh_ex.survey_data")}})
)
SELECT *
   /* ExitStudentId AS exit_student_id,
    AcademicYear AS academic_year,
    VTPName AS vtp_name,
    VCName AS vc_name,
    VTName AS vt_name,
    VTMobile AS vt_mobile_number,
Sector,
    JobRole AS job_role,
State,
Division,
District,
    NameOfSchool AS school_name,
    UdiseCode AS school_udise,
Class,
SeatNo,
    StudentUniqueId AS student_unique_id,
    StudentFirstName AS first_name,
    StudentMiddleName AS middle_name,
    StudentLastName AS last_name,
    StudentFullName AS fullname,
    Gender AS gender,
    DOB AS date_of_birth,
    FatherName AS father_name,
    MotherName AS mother_name,
Category,
Religion,
    StreamName AS stream_name,
    StudentMobileNo AS primary_contact_number,
    StudentWhatsAppNo AS alternate_number_preferably_whatsapp,
    ParentMobileNo AS parent_mobile_no,
    cityofresidence AS city_of_residence,
    districtofresidence AS district_of_residence,
    blockofresidence AS block_of_residence,
    StudentAddress,
    DoneInternship AS completed_ojt_internship_in_11_12,
    InternshipCompletedSector AS internship_completed_sector,
    WillContHigherStudies AS would_you_conti_high_edu,
    IsFullTime AS course_full_time_part_time,
    CourseToPursue AS which_course_will_you_pursue,
    OtherCourse AS other_course,
    StreamOfEducation AS stream_of_education,
    OtherStreamStudying AS specify_other_stream,
    WillContVocEdu AS will_cont_voc_edu,
    WillContVocational11 AS willing_to_conti_ve_in_11th,
    ReasonsNOTToContinue AS reasons_not_conti_ve_in_11th,
    WillContSameSector AS will_cont_same_sector,
    SectorForTraining AS sector_for_training,
    OtherSector AS other_sector,
    CurrentlyEmployed AS are_you_currently_working_job_own_business_etc,
    WorkTitle AS details_of_current_employment_title,
    DetailsOfEmployment AS details_of_employment,
    SectorsOfEmployment AS sectors_of_employment,
    IsVSCompleted AS is_vs_completed,
    WantToPursueAnySkillTraining AS willing_to_cont_skill_training,
    IsFulltimeWillingness AS is_fulltime_willingness,
    HveRegisteredOnEmploymentPortal AS hve_registered_on_employment_portal,
    EmploymentPortalName AS employment_portalname,
    WillingToGetRegisteredOnNAPS AS registered_on_naps_portal_for_apprentices,
    IntrestedInJobOrSelfEmploymentPost12th AS interested_in_job_or_self_employment_after_10_12,
    PreferredLocations AS preferred_location_for_employment,
    ParticularLocation AS particular_location_for_employment ,
WantToKnowAboutOpportunities,
    CanLahiGetInTouch AS concent_for_lahi_contact,
    WantToKnowAbtPgmsForJobsNContEdu AS want_to_know_abtpgms_for_jobsn_cont_edu,
    CollectedEmailId AS collected_email_id,
    SurveyCompletedByStudentORParent AS survey_completed_by_student_or_parent,
    DateOfIntv AS date_of_exit_interview,
    Remark AS remark,
    ExitSurveyStatus AS exit_survey_status,
    IsRelevantToVocCourse AS is_relevant_to_voc_course,
    WillBeFullTime AS will_be_fulltime,
    OtherReasons AS other_reasons,
    DoesFieldStudyHveVocSub AS does_field_study_hve_voc_sub,
    InterestedInJobOrSelfEmployment AS intrested_in_job_or_self_employment_post12th,
    TopicsOfInterest AS topics_of_interest,
    AnyPreferredLocForEmployment AS any_preferred_loc_for_employment,
    CanSendTheUpdates AS can_send_the_updates,
StudentWANo,
    WillingToContSkillTraining AS interested_in_skill_training,
    CourseForTraining AS course_for_training,
    CourseNameIfOther AS course_name_if_other,
    SkillTrainingType AS skill_training_type,
    OtherSectorsIfAny AS other_sectors_if_any,
WantToKnowAbtSkillsUnivByGvt,
TrainingType,
    SectorForSkillTraining AS sector_for_skill_training,
    OthersIfAny AS others_if_any,
    WillingToGoForTechHighEdu AS willing_to_go_for_tech_high_edu,
    DifferentProgramOpportunities AS different_program_opportunities,
    IsAssessmentRequired AS is_assessment_required,
    AssessmentConducted AS assessment_conducted,
    SubmissionDate AS submission_time,
    "start_date" AS "start_date",
    "end_date" AS "end_date",
    "today" AS "today",
    "select_sector" AS "select_sector",
    "id" AS "id",
    "uuid"  AS "uuid",
    "index" AS "index",
    "student_unique_id_new" AS "student_unique_id_new",
    "firm_organisation_name" AS "firm_organisation_name",
    "firm_contact_number" AS "firm_contact_number",
 	"firm_city_location" AS "firm_city_location",
    "details_ojt_internship_employer" AS "details_ojt_internship_employer",
    "reason_not_conti_high_educ" AS "reason_not_conti_high_educ",
    "reason_not_conti_high_educ_financial" AS "reason_not_conti_high_educ_financial",
    "reason_not_conti_high_educ_need_a_job" AS "reason_not_conti_high_educ_need_a_job",
    "reason_not_conti_high_educ_family_not_allow" AS "reason_not_conti_high_educ_family_not_allow",
    "reason_not_conti_high_educ_not_interested" AS "reason_not_conti_high_educ_not_interested",
    "reason_not_conti_high_educ_failed_in_current" AS "reason_not_conti_high_educ_failed_in_current",
    "reason_not_conti_high_educ_school_till_10th_only" AS "reason_not_conti_high_educ_school_till_10th_only",
    "reason_not_conti_high_educ_marriage"  AS "reason_not_conti_high_educ_marriage",
    "reason_not_conti_high_educ_other" AS "reason_not_conti_high_educ_other",
    "stream_of_higher_educ" AS "stream_of_higher_educ",
    "other_educ_stream_please_specify" AS "other_educ_stream_please_specify",
    "field_studies_contain_voc_subjects" AS "field_studies_contain_voc_subjects",
    "reasons_for_not_conti_ve" AS "reasons_for_not_conti_ve",
    "other_reason_not_conti_ve_specify" AS "other_reason_not_conti_ve_specify",
    "willing_to_conti_part_time_job_while_doing_educ" AS "willing_to_conti_part_time_job_while_doing_educ",
    "kind_of_employment_are_you_interested_in" AS "kind_of_employment_are_you_interested_in",
    "interested_in_career_counseling" AS "interested_in_career_counseling",
    "overall_ve_experience_in_school" AS "overall_ve_experience_in_school",
    "are_you_intrested_in_doing_apprentice_naps_" AS "are_you_intrested_in_doing_apprentice_naps_",
    "parent_index" AS "parent_index",
    "submission_id" AS "submission_id",
    "submission_uuid" AS "submission_uuid" */
 FROM cte