{{ config(
  materialized='table')}}

WITH cte AS (
SELECT
    distinct ExitStudentId AS exit_student_id,
    AcademicYear AS academic_year,
    VTPName::NAME AS vtp_name,
    VCName AS vc_name,
    VTName::NAME AS vt_name,
    VTMobile AS vt_mobile_number,
Sector,
    JobRole AS job_role,
State,
Division,
District,
    NameOfSchool AS school_name,
    UdiseCode AS school_udise,
Class,
    StudentUniqueId AS student_unique_id,
    StudentFirstName AS first_name,
    StudentMiddleName AS middle_name,
    StudentLastName AS last_name,
    StudentFullName::NAME AS fullname,
    Gender AS gender,
    DOB AS date_of_birth,
    Left(cast(AGE(DOB) as Varchar(20)),2) AS age,
    FatherName::NAME AS father_name,
    MotherName::NAME AS mother_name,
Category,
Religion,
    StreamName AS stream_name,
    StudentMobileNo AS primary_contact_number,
    StudentWhatsAppNo AS alternate_number_preferably_whatsapp,
    ParentMobileNo AS parent_mobile_no,
    cityofresidence AS city_of_residence,
    districtofresidence AS district_of_residence,
    blockofresidence AS block_of_residence,
    StudentAddress,
    DoneInternship AS completed_ojt_internship_in_11_12,
    InternshipCompletedSector AS internship_completed_sector,
    WillContHigherStudies AS would_you_conti_high_edu,
    IsFullTime AS course_full_time_part_time,
    CourseToPursue AS which_course_will_you_pursue,
    OtherCourse AS other_course,
    StreamOfEducation AS stream_of_education,
    OtherStreamStudying AS specify_other_stream,
    WillContVocEdu AS will_cont_voc_edu,
    WillContVocational11 AS willing_to_conti_ve_in_11th,
    ReasonsNOTToContinue AS reasons_not_conti_ve_in_11th,
    WillContSameSector AS will_cont_same_sector,
    SectorForTraining AS sector_for_training,
    OtherSector AS other_sector,
    CurrentlyEmployed AS are_you_currently_working_job_own_business_etc,
    WorkTitle AS details_of_current_employment_title,
    DetailsOfEmployment AS details_of_employment,
    SectorsOfEmployment AS sectors_of_employment,
    IsVSCompleted AS is_vs_completed,
    WantToPursueAnySkillTraining AS willing_to_cont_skill_training,
    IsFulltimeWillingness AS is_fulltime_willingness,
    HveRegisteredOnEmploymentPortal AS hve_registered_on_employment_portal,
    EmploymentPortalName AS employment_portalname,
    WillingToGetRegisteredOnNAPS AS registered_on_naps_portal_for_apprentices,
    IntrestedInJobOrSelfEmploymentPost12th AS interested_in_job_or_self_employment_after_10_12,
    PreferredLocations AS preferred_location_for_employment,
    ParticularLocation AS particular_location_for_employment ,
WantToKnowAboutOpportunities,
    CanLahiGetInTouch AS concent_for_lahi_contact,
    WantToKnowAbtPgmsForJobsNContEdu AS want_to_know_abtpgms_for_jobsn_cont_edu,
    CollectedEmailId AS collected_email_id,
    SurveyCompletedByStudentORParent AS survey_completed_by_student_or_parent,
    DateOfIntv AS date_of_exit_interview,
    Remark AS remark,
    ExitSurveyStatus AS exit_survey_status,
    IsRelevantToVocCourse AS is_relevant_to_voc_course,
    WillBeFullTime AS will_be_fulltime,
    OtherReasons AS other_reasons,
    DoesFieldStudyHveVocSub AS does_field_study_hve_voc_sub,
    InterestedInJobOrSelfEmployment AS intrested_in_job_or_self_employment_post12th,
    TopicsOfInterest AS topics_of_interest,
    AnyPreferredLocForEmployment AS any_preferred_loc_for_employment,
    CanSendTheUpdates AS can_send_the_updates,
StudentWANo,
    WillingToContSkillTraining AS interested_in_skill_training,
    CourseForTraining AS course_for_training,
    CourseNameIfOther AS course_name_if_other,
    SkillTrainingType AS skill_training_type,
    OtherSectorsIfAny AS other_sectors_if_any,
WantToKnowAbtSkillsUnivByGvt,
TrainingType,
    SectorForSkillTraining AS sector_for_skill_training,
    OthersIfAny AS others_if_any,
    WillingToGoForTechHighEdu AS willing_to_go_for_tech_high_edu,
    DifferentProgramOpportunities AS different_program_opportunities,
    IsAssessmentRequired AS is_assessment_required,
    AssessmentConducted AS assessment_conducted,
    SubmissionDate::TIMESTAMP AS submission_time,
    CAST(NULL AS TIMESTAMP) AS "start_date",
    CAST(NULL AS TIMESTAMP)  AS "end_date",
    CAST(NULL AS DATE) AS "today",
    CAST(NULL AS VARCHAR(20)) AS "select_sector",
    CAST(NULL AS VARCHAR(20)) AS "id",
    CAST(NULL AS VARCHAR(20)) AS "uuid",
    CAST(NULL AS VARCHAR(20)) AS "index",
    CAST(NULL AS VARCHAR(30)) AS "firm_organisation_name",
    CAST(NULL AS VARCHAR(20)) AS "firm_contact_number",
    CAST(NULL AS VARCHAR(20)) AS "firm_city_location",
    CAST(NULL AS VARCHAR(20)) AS "details_ojt_internship_employer",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_financial",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_need_a_job",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_family_not_allow",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_not_interested",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_failed_in_current",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_school_till_10th_only",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_marriage",
    CAST(NULL AS VARCHAR(20)) AS "reason_not_conti_high_educ_other",
    CAST(NULL AS VARCHAR(20)) AS "stream_of_higher_educ",
    CAST(NULL AS VARCHAR(20)) AS "other_educ_stream_please_specify",
    CAST(NULL AS VARCHAR(20)) AS "field_studies_contain_voc_subjects",
    CAST(NULL AS VARCHAR(20)) AS "reasons_for_not_conti_ve",
    CAST(NULL AS VARCHAR(20)) AS "other_reason_not_conti_ve_specify",
    CAST(NULL AS VARCHAR(20)) AS "willing_to_conti_part_time_job_while_doing_educ",
    CAST(NULL AS VARCHAR(20)) AS "kind_of_employment_are_you_interested_in",
    CAST(NULL AS VARCHAR(20)) AS "interested_in_career_counseling",
    CAST(NULL AS VARCHAR(20)) AS "overall_ve_experience_in_school",
    CAST(NULL AS VARCHAR(20)) AS "are_you_intrested_in_doing_apprentice_naps_",
    CAST(NULL AS VARCHAR(20)) AS "parent_index",
    CAST(NULL AS VARCHAR(20)) AS "submission_id",
    CAST(NULL AS VARCHAR(20)) AS "submission_uuid"
FROM {{ref('int_lh_jh_ex.survey_23-24')}}
)
SELECT * FROM cte
